<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <NeutralLanguage>en</NeutralLanguage>
    <Product>Network Optimizer</Product>
    <Company>Network Optimizer</Company>
    <Authors>Network Optimizer</Authors>
    <Version>1.2.0</Version>
    <Copyright>Copyright (c) Network Optimizer</Copyright>
  </PropertyGroup>
</Project>
